name: Build VyOS LTS

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
# on:
#   push:
#     tags:
#       - 'v*'
on:
  workflow_dispatch  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
       format: "YYYYMMDDHHmmss"

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:sagitta
        
    - name: Build iso
      run: |
        git clone -b sagitta --single-branch https://github.com/vyos/vyos-build
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:sagitta bash -c 'sudo make clean && sudo ./build-vyos-image iso --architecture amd64 --build-type release --version "${{ steps.date.outputs.time  }}"'

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.myToken }}
        file: vyos-build/build/vyos-${{ steps.date.outputs.time  }}-amd64.iso
        tag: equuleus-${{ steps.date.outputs.time  }}
        overwrite: true
        file_glob: true
  
  
